#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the zip network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0x2d,0x57,0x50,0x51,0x6d,0xb0,
    0x01,0x04,0x81,0x97,0xa4,0xca,0x6d,0xb0,
};

static const uint8_t chainparams_seed_test[] = {
    0x01,0x04,0x81,0x97,0xa4,0xca,0x94,0xc0,
};
#endif // BITCOIN_CHAINPARAMSSEEDS_H
